# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/ui/widget_sessions_tab.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget_sessions_tab(object):
    def setupUi(self, widget_sessions_tab):
        widget_sessions_tab.setObjectName("widget_sessions_tab")
        widget_sessions_tab.resize(662, 330)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(widget_sessions_tab.sizePolicy().hasHeightForWidth())
        widget_sessions_tab.setSizePolicy(sizePolicy)
        widget_sessions_tab.setMaximumSize(QtCore.QSize(99999, 99999))
        self.verticalLayout = QtWidgets.QVBoxLayout(widget_sessions_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(widget_sessions_tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.projects_combo_box = QtWidgets.QComboBox(widget_sessions_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projects_combo_box.sizePolicy().hasHeightForWidth())
        self.projects_combo_box.setSizePolicy(sizePolicy)
        self.projects_combo_box.setObjectName("projects_combo_box")
        self.horizontalLayout.addWidget(self.projects_combo_box)
        self.push_btn_start_stop = QtWidgets.QPushButton(widget_sessions_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_btn_start_stop.sizePolicy().hasHeightForWidth())
        self.push_btn_start_stop.setSizePolicy(sizePolicy)
        self.push_btn_start_stop.setObjectName("push_btn_start_stop")
        self.horizontalLayout.addWidget(self.push_btn_start_stop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.label_ongoing = QtWidgets.QLabel(widget_sessions_tab)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_ongoing.setFont(font)
        self.label_ongoing.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ongoing.setObjectName("label_ongoing")
        self.verticalLayout.addWidget(self.label_ongoing)
        self.frame_report = QtWidgets.QFrame(widget_sessions_tab)
        self.frame_report.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_report.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_report.setLineWidth(0)
        self.frame_report.setObjectName("frame_report")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_report)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_time_spent_description = QtWidgets.QLabel(self.frame_report)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_time_spent_description.setFont(font)
        self.label_time_spent_description.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_time_spent_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_spent_description.setObjectName("label_time_spent_description")
        self.verticalLayout_2.addWidget(self.label_time_spent_description)
        self.label_time_spent_value = QtWidgets.QLabel(self.frame_report)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time_spent_value.sizePolicy().hasHeightForWidth())
        self.label_time_spent_value.setSizePolicy(sizePolicy)
        self.label_time_spent_value.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.label_time_spent_value.setFont(font)
        self.label_time_spent_value.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_time_spent_value.setScaledContents(False)
        self.label_time_spent_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time_spent_value.setWordWrap(False)
        self.label_time_spent_value.setObjectName("label_time_spent_value")
        self.verticalLayout_2.addWidget(self.label_time_spent_value)
        spacerItem3 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.label_total = QtWidgets.QLabel(self.frame_report)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_total.setFont(font)
        self.label_total.setAlignment(QtCore.Qt.AlignCenter)
        self.label_total.setObjectName("label_total")
        self.verticalLayout_2.addWidget(self.label_total)
        self.verticalLayout.addWidget(self.frame_report)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)

        self.retranslateUi(widget_sessions_tab)
        QtCore.QMetaObject.connectSlotsByName(widget_sessions_tab)

    def retranslateUi(self, widget_sessions_tab):
        _translate = QtCore.QCoreApplication.translate
        widget_sessions_tab.setWindowTitle(_translate("widget_sessions_tab", "widget_sessions_tab"))
        self.label.setText(_translate("widget_sessions_tab", "Choose a project to work with:"))
        self.push_btn_start_stop.setText(_translate("widget_sessions_tab", "Start"))
        self.label_ongoing.setText(_translate("widget_sessions_tab", "There is an ongoing working session for this project."))
        self.label_time_spent_description.setText(_translate("widget_sessions_tab", "Time spent (last session)"))
        self.label_time_spent_value.setText(_translate("widget_sessions_tab", "99:99:99"))
        self.label_total.setText(_translate("widget_sessions_tab", "Total: 9999 days, 23:59:59"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_sessions_tab = QtWidgets.QWidget()
    ui = Ui_widget_sessions_tab()
    ui.setupUi(widget_sessions_tab)
    widget_sessions_tab.show()
    sys.exit(app.exec_())
